id: AA044C419
title: Prayer to Khandro Tsering Chödrön
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:18:14.415031
  last_modified_at: 2022-03-01 00:18:14.415038
