id: AA044C419
title: 'Beautiful String of Jewels: A Heart Advice'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:18:14.404480
  last_modified_at: 2022-03-01 00:18:14.404488
