id: AA044C419
title: Prayer for the Long Life of Khandro Tsering Chödrön
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:18:14.411260
  last_modified_at: 2022-03-01 00:18:14.411264
